### ISSUE TITLE
github branches 

### ISSUE THREAD

**Issue by rowanibrahem** [Eman-Sheta/Chat_App#2]
احنا بنعمل برانش dev و لكل فيتشر عندنا برانش منفصل فال splash كان مفروض يكون ليها برانش

**Comment by Eman-Sheta** [comment]
مش فاهمه قصد حضرتك بصراحه

**Comment by Eman-Sheta** [comment]
بس ممكن أنا فاهمه غلط

**Comment by Eman-Sheta** [comment]
تم
