### ISSUE TITLE
core & features issues 

### ISSUE THREAD

**Issue by rowanibrahem** [Eman-Sheta/Chat_App#3]
فين تقسيمة الcore يا ايمان و الfeatures مش مظبوطة انتي سمعتي سيشن الmvvm ؟

**Comment by Eman-Sheta** [comment]
اه سمعتها

**Comment by Eman-Sheta** [comment]
بس أنا مش فاهمه أوي يعني دا على قد اللي فهمته

**Comment by Eman-Sheta** [comment]
كدا تمام
